name: CICD
run-name: CICD capture chart

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  IMAGE: ai-agent/pluton-service-capture-chart
  YAML_FILE_NAME: pluton-service-capture-chart
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true
      - name: Set Image tag
        id: vars
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: service-capture-chart
          tags: ${{ steps.login-ecr.outputs.registry }}/${{env.IMAGE}}:${{steps.vars.outputs.tag}}
          push: true
          file: service-capture-chart/Dockerfile

      - name: Checkout to pluton-infra
        uses: actions/checkout@v4
        with:
          repository: PlutonAi-HQ/pluton-infra
          ref: main
          token: ${{ secrets.PAT_ACCESS_TOKEN }}
      - name: Edit deployment
        run: |
          sed -i "s|image: .*${{ env.YAML_FILE_NAME }}:.*|image: ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE }}:${{ steps.vars.outputs.tag }}|" deployment/${{ env.YAML_FILE_NAME }}.yaml

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add deployment/${{ env.YAML_FILE_NAME }}.yaml

          git commit -m "chore(${{ env.YAML_FILE_NAME }}): Update ${{ env.YAML_FILE_NAME }} image tag to ${{ steps.vars.outputs.tag }}"
          git rebase
          git push
